ManyBook/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('account/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from books.views import (
        home,
        addbook,\
        # me,
        bookview,\
        catview,
        search,
        addtoshelf,
        bookshelf,
        pdfviewer,
        deletebook,
        setcurrentbook,
        setcurrentpage,
        downloaded,
        uploadslist,
        downloadlist,
        checkisbn,
        setrating,
        newcomment,
        newreply,
        deletecomment,
        deletereply,
        # trial,
)

app_name = 'books'

urlpatterns = [
        path('', home, name='home'),
        path('addbook/', addbook, name='addbook'),
        path('book/', bookview, name='bookview'),
        path('cat/', catview, name='catview'),
        path('search/', search, name='search'),
        path('addtoshelf/', addtoshelf, name='addtoshelf'),
        path('bookshelf/', bookshelf, name='bookshelf'),
        path('bookview/', pdfviewer, name='pdfviewer'),
        path('deleteshelf/', deletebook, name='deleteshelf'),
        path('setcurrentbook/', setcurrentbook, name='setcurrentbook'),
        path('setcurrentpage', setcurrentpage, name='setcurrentpage'),
        path('download/', downloaded, name='downloaded'),
        path('uploadlist', uploadslist, name='uploadslist'),
        path('downloadlist/', downloadlist, name='downloadlist'),
        path('checkisbn/', checkisbn, name='checkisbn'),
        path('setrating/', setrating, name='setrating'),
        path('newcomment/', newcomment, name='newcomment'),
        path('newreply/', newreply, name='newreply'),
        path('deletecomment/', deletecomment, name='deletecomment'),
        path('deletereply/', deletereply, name='deletereply'),
        # path('trial/', trial, name='trial'),
]

books/models.py
from django.db import models
from account.models import Account
from multiselectfield import MultiSelectField
from django.utils import timezone

class Genre(models.Model):
    name = models.CharField(max_length=100, null=False, unique=True)

    def __str__(self):
        return self.name

class Language(models.Model):
    lang        = models.CharField(max_length=30,primary_key=True)

    def __str__(self):
        return self.lang

class Book(models.Model):

    title           = models.CharField(max_length=120, null=False, blank=False)
    author          = models.CharField(max_length=40, null=False, blank=False)
    series          = models.CharField(max_length=20)
    genre           = models.ManyToManyField(Genre)
    language        = models.ForeignKey(Language, on_delete=models.CASCADE)
    description     = models.CharField(max_length=1536, null=False, blank=False)
    isbn            = models.CharField(max_length=13, unique=True, null=False)
    file            = models.FileField(upload_to='pdf/')
    cover           = models.ImageField(upload_to='covers/', null=True, blank=True)
    views           = models.IntegerField(default=0)
    user            = models.ForeignKey(Account, on_delete=models.CASCADE)
    totalrating     = models.PositiveSmallIntegerField(default=0)
    ratingcount     = models.PositiveIntegerField(default=0)
    created_at      = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class BookShelf(models.Model):
    user                = models.ForeignKey(Account, on_delete=models.CASCADE)
    book                = models.ForeignKey(Book, on_delete=models.CASCADE)
    iscurrentbook       = models.BooleanField(default=False)
    currentpage         = models.PositiveIntegerField(default=1)
    totalpage           = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.user.username

class Downloads(models.Model):
    user                = models.ForeignKey(Account, on_delete=models.CASCADE)
    book                = models.ForeignKey(Book, on_delete=models.CASCADE)
    created_at          = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return self.book.title

class Comment(models.Model):
    book        = models.ForeignKey(Book, on_delete=models.CASCADE)
    user        = models.ForeignKey(Account, on_delete=models.CASCADE)
    text        = models.CharField(max_length=512, null=False)
    likes       = models.PositiveIntegerField(default=0)
    dislikes    = models.PositiveIntegerField(default=0)
    created_at  = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)


class Reply(models.Model):
    class Meta:
        ordering = ['-created_at']
        
    comment     = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user        = models.ForeignKey(Account, on_delete=models.CASCADE)
    text        = models.CharField(max_length=512, null=False)
    likes       = models.PositiveIntegerField(default=0)
    dislikes    = models.PositiveIntegerField(default=0)
    created_at  = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

class Rating(models.Model):
    book        = models.ForeignKey(Book, on_delete=models.CASCADE)
    user        = models.ForeignKey(Account, on_delete=models.CASCADE)
    userrating  = models.PositiveSmallIntegerField(default=0, null=False)

    def __str__(self):
        return str(self.userrating)


class Barcode(models.Model):

    long_url     = models.URLField(primary_key=True)
    short_url    = models.URLField(default="")
    image        = models.FileField(upload_to='images/barcodes/')

    def __str__(self):
        return str(self.long_url)

books/forms.py
from django import forms

from .models import Book
from account.models import Account


class AddBook(forms.ModelForm):
    class Meta:
        model = Book
        fields = (
            'title',
            'author',
            'series',
            'language',
            'isbn',
            'file',
            'genre',
            'cover',
            'description',
            'user'
        )

    title  = forms.CharField(widget=forms.TextInput(
            attrs={
                'class':'formcontrol itemToBeFocused',
                'required':'false',
            }
        ))

    author  = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'formcontrol itemToBeFocused',
        }
    ))

    series  = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'formcontrol itemToBeFocused',
        }
    ))

    isbn  = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'formcontrol itemToBeFocused',
        }
    ))

    description = forms.CharField(widget=forms.Textarea())

    def save(self):
        instance  = super(AddBook, self).save()
        instance.genre.clear()
        instance.genre.add(*self.cleaned_data['genre'])
        return instance

books/views.py
import json

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse, HttpResponse
from django.utils import timezone
from django.db.models import Q
from django.utils.text import wrap
from django.db.models.functions import Lower

from account.models import Account

from .forms import AddBook
from .models import Book, BookShelf, Downloads, Genre, Language, Rating, Reply, Comment, Barcode

import requests,barcode
from django.core.files import File

# def trial(request):
#     return render(request, 'books/trial2.html')

@login_required
def pdfviewer(request):
    context = {}
    if request.method == 'GET':
        if request.GET['isbn'] :
            context['isbn'] = request.GET['isbn']
            context['book'] = Book.objects.get(isbn = request.GET['isbn'])
            try:
                context['page'] = BookShelf.objects.get(user=request.user, book=context['book']).currentpage
            except BookShelf.DoesNotExist:
                context['page'] = 1
    return render(request, 'books/pdfviewer.html',context)


def home(request):
    context = {}
    context['search'] = True
    if request.user.is_authenticated:
        context['auth'] = True
    allBooks = Book.objects.all()
    context['mostviewed'] = allBooks.order_by('-views')[:12]
    context['new'] = allBooks.order_by('-created_at')[:12]
    return render(request, 'books/index.html', context)

@login_required
def addbook(request):
    context = {}
    context['addbookActive'] = True
    context['auth'] = True
    form = AddBook(initial = {'user':request.user})
    if request.method == 'POST':
        form = AddBook(request.POST, request.FILES, initial = {'user':request.user})
        if form.is_valid():
            book = form.save()
            response = HttpResponse(status=302)
            response['Location'] = '/book?isbn='+str(book.isbn)
            return response
            form = AddBook(initial = {'user':request.user})
    context['form'] = form;
    context['genres'] = Genre.objects.all()
    context['languages'] = Language.objects.all()
    return render(request, 'books/addbook2.html', context)


def bookview(request,isbn=None):
    context = {}
    context['search'] = True
    if request.user.is_authenticated:
        context['auth'] = True
    if request.method=='GET':
        if request.GET.get('isbn'):
            isbn = request.GET.get('isbn')
    if isbn == None:
        return redirect('books:home')
    book = Book.objects.get(isbn=isbn)
    context['book'] = book
    bookrating = Rating.objects.filter(book=book).count()
    if bookrating == 0:
        context['ratingnumber'] = 0
    else:
        context['ratingnumber'] = bookrating
    if request.user.is_authenticated:
        if Rating.objects.filter(book=book, user=request.user).count() == 0:
            context['userRated'] = False
        else:
            context['userRated'] = True
            context['userrating'] = Rating.objects.get(book=book,user=request.user).userrating
    else:
        context['userRated'] = False
    context['comments'] = Comment.objects.filter(book=book).order_by('-created_at')
    context['morefromauthor'] = Book.objects.filter(author=book.author).exclude(isbn=book.isbn)[:6]

    #get or generate barcode
    barcode = gen_or_get_barcode(request)
    context['barcode'] = barcode

    return render(request, 'books/bookview.html', context)



def catview(request):
    context = {}
    context['search'] = True
    context['languages'] = Language.objects.all()
    context['genres'] = Genre.objects.all()
    if request.user.is_authenticated:
        context['auth'] = True
    if request.method == 'POST':
        sort = request.POST.get('sort','az')
        lang = request.POST.get('language','all')
        gen = request.POST.get('category','all')
        print('lang print next')
        print(request.POST.get('category'))
        books = Book.objects.select_related('language').all()
        if lang != 'all':
            language = Language.objects.get(lang=lang)
            books = books.filter(language = language)
        if gen != 'all':
            genre = Genre.objects.get(name=gen)
            books = books.filter(genre=genre)
        if sort == 'az':
            books = books.order_by(Lower('title'))
        elif sort == 'za':
            books = books.order_by(Lower('title')).reverse()
        elif sort == 'no':
            books = books.order_by('-created_at')
        else:
            books = books.order_by('created_at')
        context['cat'] = books
        context['selectedsort'] = sort
        context['selectedlang'] = lang
        context['selectedgen'] = gen
        return render(request, 'books/catview1.html', context)
    if request.method == 'GET':
        cat = request.GET.get('cat')
        context['title'] = cat
        context['cat'] = Book.objects.filter(genre = Genre.objects.get(name = cat))
    return render(request, 'books/catview1.html', context)

@login_required
def search(request):
    context ={}
    context['search'] = True
    if request.user.is_authenticated:
        context['auth'] = True
    context['title'] = 'Search Results'
    if request.method == 'GET':
        q = request.GET.get('search')
        context['cat'] = Book.objects.filter(Q(title__icontains=q) | Q(author__icontains=q) | Q(description__icontains=q))
    return render(request, 'books/searchview.html', context)

@login_required
def addtoshelf(request):
    context = {'status':'err'}
    if request.method == "GET":
        isbn = request.GET.get('isbn')
        book = Book.objects.get(isbn=isbn)
        user = request.user
        try:
            bookadded = BookShelf.objects.filter(book=book).filter(user= Account.objects.get(username=request.user))
            context['status'] = 'pre'
        except BookShelf.DoesNotExist:
            text = Book.objects.get(isbn = isbn)
            text.views+=1
            text.save()
            newbook=BookShelf(user=Account.objects.get(username=request.user), book=text)
            newbook.save()
            context['status'] = 'ok'
        if not bookadded:
            text = Book.objects.get(isbn = isbn)
            text.views+=1
            text.save()
            newbook=BookShelf(user=Account.objects.get(username=request.user), book=text)
            newbook.save()
            context['status'] = 'ok'
    return JsonResponse(context)

def bookshelf(request):
    context = {}
    context['auth'] = False
    context['bookshelfActive'] = True
    context['search'] = True
    if request.user.is_authenticated:
        context['auth'] = True
        context['books'] = BookShelf.objects.filter(user=request.user)
        try:
            context['currentbook'] = context['books'].get(iscurrentbook=True)
            if context['currentbook'].totalpage == 0:
                context['percent'] = 0;
            else:
                context['percent'] = context['currentbook'].currentpage / context['currentbook'].totalpage * 100
        except BookShelf.DoesNotExist:
            pass
    return render(request, 'books/bookshelf1.html', context)

@login_required
def deletebook(request):
    context = {'status':'err'}
    if request.method == 'GET':
        isbn = request.GET.get('isbn')
        try:
            book = Book.objects.get(isbn=isbn)
        except Book.DoesNotExist:
            return JsonResponse(context)
        bookinshelf = BookShelf.objects.filter(book=book).filter(user=request.user)
        bookinshelf.delete()
        context['status'] = 'ok'
    return JsonResponse(context)

@login_required
def setcurrentbook(request):
    if request.method == 'GET':
        try:
            previousbook = BookShelf.objects.get(user=request.user, iscurrentbook=True)
            previousbook.iscurrentbook = False
            previousbook.save()
        except BookShelf.DoesNotExist:
            pass
        isbn = request.GET.get('isbn')
        try:
            book = Book.objects.get(isbn=isbn)
        except Book.DoesNotExist:
            print('Error in getting book')
            return
        item = BookShelf.objects.get(book=book, user=request.user)
        item.iscurrentbook = True
        item.save()
    return

@login_required
def setcurrentpage(request):
    print('got request')
    if request.method == 'GET':
        currentbook = BookShelf.objects.get(user=request.user, iscurrentbook=True)
        pageno = request.GET.get('page')
        totalpage = request.GET.get('total')
        print('in if ')
        if int(pageno) > currentbook.currentpage:
            currentbook.currentpage = pageno
            currentbook.totalpage = int(totalpage)
            currentbook.save()
            print('saved')
    return JsonResponse({'result':'done'})

@login_required
def uploadslist(request):
    context = {}
    context['uploadActive'] = True
    context['search'] = True
    if request.user.is_authenticated:
        context['auth'] = True
    if request.method == 'GET':
        booklist = Book.objects.filter(user=request.user)
        page = request.GET.get('page',1)
        paginator = Paginator(booklist.order_by('-created_at'),10)
        context['books'] = paginator.get_page(page)
        context['length'] = booklist.count()
        context['cat'] = 'Uploads'
        context['upload'] = True
    return render(request, 'books/uploads.html', context)

@login_required
def downloadlist(request):
    context = {}
    context['downloadActive'] = True
    context['search'] = True
    if request.user.is_authenticated:
        context['auth'] = True
    if request.method == 'GET':
        booklist = Downloads.objects.filter(user = request.user)
        page = request.GET.get('page',1)
        paginator = Paginator(booklist.order_by('-created_at'),10)
        context['booksdown'] = paginator.get_page(page)
        context['cat'] = 'Downloads'
        context['download'] = True

books/templates/old/addbook1.html
{% extends 'books/base.html' %}
{% load static %}

{% block exlinks %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/main_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/responsive.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> -->
<!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
<link href="https://fonts.googleapis.com/css?family=Amatic+SC:700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
{% endblock %}

		{% block extra %}
		<div class="bookadded">
          <p class="newbookadded">New Book Added</p>
          <hr class="bookaddedhr">
          <p class="booktitle">{% if booktitle %}{{booktitle}}{% endif %}</p>
          <p class="bookauthor">by <em>{% if bookauthor %}{{bookauthor}}{% endif %}</em></p>
        </div>
		{% endblock %}

		{% block js %}
		var currentlyBlurred;
        $(document).ready(function(){
            $(".itemToBeFocused").focus(function () {
                    var inputfields = $('.itemToBeFocused');
                    for(i=0;i<inputfields.len;i++){
                      inputfields[i].removeClass('focused');
                    }
                    currentlyBlurred = $(':focus');
                    $(currentlyBlurred).addClass('focused');
                })
            $(".itemToBeFocused").blur(function () {
                    $(currentlyBlurred).removeClass('focused');
                })
        var popupInterval;
        function clearpopup(){
          clearInterval(popupInterval);
          $('.bookadded').fadeOut();
        }
        {% if result %}
        popupInterval = setInterval(clearpopup,3000);
        $('.bookadded').fadeIn(1000);
        {% endif %}
        });
		{% endblock %}

		{% block css %}
		.submitbtn{
			background-color: #00FA9A;
			border-radius: 1px;
			padding: 5px 10px;
			color : #fff;
		}
		.submitbtn:hover{
			border:none;
			box-shadow: 0 0 5px 2px #555;
		}
		.formcontrol{
			border: none;
			border-bottom: 1px solid grey;
			width:100%;
		}

		.focused{
		  border-bottom: 2px solid #007cc4;
		}
		.inputerror{
			border: none;
			border-bottom: 1px solid grey;
		}
		.alter{
		  font-size: small;
		}
		.err{
		  color:red;
		}
		.bookadded{
		  position:fixed;
		  top: 150px;
		  right:50px;
		  width:500px;
		  height:200px;
		  border: 1px solid grey;
		  box-shadow: 0 0 5px 2px #555;
		  padding:30px 20px;
		  background-color: #fff;
		  display:none;
		}
		.newbookadded{
		  font-size: 1.5em;
		}
		.bookaddedhr{
		  border:none;
		  background-color: #007cc4;
		  height:2px;

		}
		.booktitle{
		  font-size: 1.3em;
		  margin-bottom: 10px;
		  margin-left: 15px;
		}
		.bookauthor{
		  color: #555;
		  margin-left: 15px;
		}
		.bookauthorname{
		  color: # 222;
		}
		.addbookheading{
			font-size: 1.6em;
		}
		.backarrow{
		  font-size:.9em;
		}
		a:hover{
			text-decoration:none;
		}
		#mainnav{
			margin-top: 1rem;
		}
		{% endblock %}

		{% block content %}
		<div class="col-sm-12" style='height:120px;'>

		</div>
		<div class="row">
			<div class="col-lg-6 offset-lg-3">
				<div class="section_title text-center">Add Book</div>
			</div>
		</div>
		<div class="row my-5 mx-4">
            <div class="col-md-4 col-sm-1"></div>
            <div class="col-md-4 col-sm-10">
                <form class="" action="{% url 'books:addbook'%}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                            <div class="form-group row mb-5">
                                <label for="id_title" class="col-sm-3 col-form-label">Title</label>
                                <div class="col-sm-9">
                                    <div class="row">
                                        {{ form.title }}
                                    </div>
                                    <div class="row">
                                        {% if form.title.errors %}
                                          {% for err in form.title.errors %}
                                            <p class='alter err'>{{ err }}</p>
                                          {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>


                            <div class="form-group row mb-5">
                                <label for="id_title" class="col-sm-3 col-form-label">Author</label>
                                <div class="col-sm-9">
                                    <div class="row">
                                        {{ form.author }}
                                    </div>
                                    <div class="row">
                                        {% if form.author.errors %}
                                          {% for err in form.author.errors %}
                                            <p class='alter err'>{{ err }}</p>
                                          {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>


                            <div class="form-group row mb-5">
                                <label for="id_title" class="col-sm-3 col-form-label">Series</label>
                                <div class="col-sm-9">
                                    <div class="row">
                                        {{ form.series }}
                                    </div>
                                    <div class="row">
                                        {% if form.series.errors %}
                                          {% for err in form.series.errors %}
                                            <p class='alter err'>{{ err }}</p>
                                          {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row mb-5">
                                <label for="id_title" class="col-sm-3 col-form-label">Language</label>
                                <div class="col-sm-9">
                                    <div class="row">
                                        {{ form.language }}
                                    </div>
                                    <div class="row">
                                        {% if form.language.errors %}
                                          {% for err in form.language.errors %}
                                            <p class='alter err'>{{ err }}</p>
                                          {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>


                            <div class="form-group row mb-5">
                                <label for="id_title" class="col-sm-3 col-form-label">ISBN</label>
                                <div class="col-sm-9">
                                    <div class="row">
                                        {{ form.isbn }}
                                    </div>
                                    <div class="row">
                                        {% if form.isbn.errors %}
                                          {% for err in form.isbn.errors %}
                                            <p class='alter err'>{{ err }}</p>
                                          {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row mb-5">
                                <label for="id_title" class="col-sm-3 col-form-label">Description</label>
                                <div class="col-sm-9">
                                    <div class="row">
                                        {{ form.description }}
                                    </div>
                                    <div class="row">
                                        {% if form.description.errors %}
                                          {% for err in form.description.errors %}
                                            <p class='alter err'>{{ err }}</p>
                                          {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>

                    <div class="row mb-5 ml-3">
                        <div class="row">
                            <p class="genre">Genres : </p>
                        </div>
                        <div class="row">
                            {% for value,text in form.genre.field.choices %}
                                <div class="col-sm-6 mb-3">
                                    <div class="form-check">
                                      <input class="form-check-input" type="checkbox" value="{{ value }}" name="{{ form.genre.name }}" id="id_genre_{{ forloop.counter0 }}">
                                      <label class="form-check-label" for="id_genre_{{ forloop.counter0 }}">
                                        {{text}}
                                      </label>
                                    </div>
                                </div>

                            {% endfor %}
                            <div class="row">
                                {% if form.genre.errors %}
                                  {% for err in form.genre.errors %}
                                    <p class='alter err'>{{ err }}</p>
                                  {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>

                        <div class="row mb-3 ml-2">
                            <div class="form-group">
                                <label for="exampleFormControlFile1">Select Ebook (pdf) :</label>
                                {{ form.file }}
                            </div>
                            <div class="row">
                                {% if form.file.errors %}
                                  {% for err in form.file.errors %}
                                    <p class='alter err'>{{ err }}</p>
                                  {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                        <div class="row mb-3 ml-2">
                            <div class="form-group">
                                <label for="exampleFormControlFile1">Cover picture :</label>
                                {{ form.cover }}
                            </div>
                            <div class="row">
                                {% if form.cover.errors %}
                                  {% for err in form.cover.errors %}
                                    <p class='alter err'>{{ err }}</p>
                                  {% endfor %}
                                {% endif %}
                            </div>
                        </div>


                    <div class="row mb-5 mt-4">
                        <div class="col-sm-3"></div>
                        <div class="col-sm-6">
                            <input type="submit" name="addbook" value="Add Book" class="btn form-control submitbtn">
                        </div>
                        <div class="col-sm-3"></div>
                    </div>

                </form>
            </div>
            <!-- end of main div inside container -->
            <div class="col-md-4 col-sm-1"></div>
        </div>

		{% endblock %}