ManyBook/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('account/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path

from .views import (
    registration_view,
    logout_view,
    login_view,
    update_view,
)

app_name = 'account'

urlpatterns = [
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('update/', update_view, name='update'),
]

books/urls.py
from django.urls import path
from books.views import (
        home,
        addbook,\
        # me,
        bookview,\
        catview,
        search,
        addtoshelf,
        bookshelf,
        pdfviewer,
        deletebook,
        setcurrentbook,
        setcurrentpage,
        downloaded,
        uploadslist,
        downloadlist,
        checkisbn,
        setrating,
        newcomment,
        newreply,
        deletecomment,
        deletereply,
        # trial,
)

app_name = 'books'

urlpatterns = [
        path('', home, name='home'),
        path('addbook/', addbook, name='addbook'),
        path('book/', bookview, name='bookview'),
        path('cat/', catview, name='catview'),
        path('search/', search, name='search'),
        path('addtoshelf/', addtoshelf, name='addtoshelf'),
        path('bookshelf/', bookshelf, name='bookshelf'),
        path('bookview/', pdfviewer, name='pdfviewer'),
        path('deleteshelf/', deletebook, name='deleteshelf'),
        path('setcurrentbook/', setcurrentbook, name='setcurrentbook'),
        path('setcurrentpage', setcurrentpage, name='setcurrentpage'),
        path('download/', downloaded, name='downloaded'),
        path('uploadlist', uploadslist, name='uploadslist'),
        path('downloadlist/', downloadlist, name='downloadlist'),
        path('checkisbn/', checkisbn, name='checkisbn'),
        path('setrating/', setrating, name='setrating'),
        path('newcomment/', newcomment, name='newcomment'),
        path('newreply/', newreply, name='newreply'),
        path('deletecomment/', deletecomment, name='deletecomment'),
        path('deletereply/', deletereply, name='deletereply'),
        # path('trial/', trial, name='trial'),
]

books/models.py
from django.db import models
from account.models import Account
from multiselectfield import MultiSelectField
from django.utils import timezone

class Genre(models.Model):
    name = models.CharField(max_length=100, null=False, unique=True)

    def __str__(self):
        return self.name

class Language(models.Model):
    lang        = models.CharField(max_length=30,primary_key=True)

    def __str__(self):
        return self.lang

class Book(models.Model):

    title           = models.CharField(max_length=120, null=False, blank=False)
    author          = models.CharField(max_length=40, null=False, blank=False)
    series          = models.CharField(max_length=20)
    genre           = models.ManyToManyField(Genre)
    language        = models.ForeignKey(Language, on_delete=models.CASCADE)
    description     = models.CharField(max_length=1536, null=False, blank=False)
    isbn            = models.CharField(max_length=13, unique=True, null=False)
    file            = models.FileField(upload_to='pdf/')
    cover           = models.ImageField(upload_to='covers/', null=True, blank=True)
    views           = models.IntegerField(default=0)
    user            = models.ForeignKey(Account, on_delete=models.CASCADE)
    totalrating     = models.PositiveSmallIntegerField(default=0)
    ratingcount     = models.PositiveIntegerField(default=0)
    created_at      = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class BookShelf(models.Model):
    user                = models.ForeignKey(Account, on_delete=models.CASCADE)
    book                = models.ForeignKey(Book, on_delete=models.CASCADE)
    iscurrentbook       = models.BooleanField(default=False)
    currentpage         = models.PositiveIntegerField(default=1)
    totalpage           = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.user.username

class Downloads(models.Model):
    user                = models.ForeignKey(Account, on_delete=models.CASCADE)
    book                = models.ForeignKey(Book, on_delete=models.CASCADE)
    created_at          = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return self.book.title

class Comment(models.Model):
    book        = models.ForeignKey(Book, on_delete=models.CASCADE)
    user        = models.ForeignKey(Account, on_delete=models.CASCADE)
    text        = models.CharField(max_length=512, null=False)
    likes       = models.PositiveIntegerField(default=0)
    dislikes    = models.PositiveIntegerField(default=0)
    created_at  = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)


class Reply(models.Model):
    class Meta:
        ordering = ['-created_at']
        
    comment     = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user        = models.ForeignKey(Account, on_delete=models.CASCADE)
    text        = models.CharField(max_length=512, null=False)
    likes       = models.PositiveIntegerField(default=0)
    dislikes    = models.PositiveIntegerField(default=0)
    created_at  = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

class Rating(models.Model):
    book        = models.ForeignKey(Book, on_delete=models.CASCADE)
    user        = models.ForeignKey(Account, on_delete=models.CASCADE)
    userrating  = models.PositiveSmallIntegerField(default=0, null=False)

    def __str__(self):
        return str(self.userrating)


class Barcode(models.Model):

    long_url     = models.URLField(primary_key=True)
    short_url    = models.URLField(default="")
    image        = models.FileField(upload_to='images/barcodes/')

    def __str__(self):
        return str(self.long_url)

books/forms.py
from django import forms

from .models import Book
from account.models import Account


class AddBook(forms.ModelForm):
    class Meta:
        model = Book
        fields = (
            'title',
            'author',
            'series',
            'language',
            'isbn',
            'file',
            'genre',
            'cover',
            'description',
            'user'
        )

    title  = forms.CharField(widget=forms.TextInput(
            attrs={
                'class':'formcontrol itemToBeFocused',
                'required':'false',
            }
        ))

    author  = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'formcontrol itemToBeFocused',
        }
    ))

    series  = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'formcontrol itemToBeFocused',
        }
    ))

    isbn  = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'formcontrol itemToBeFocused',
        }
    ))

    description = forms.CharField(widget=forms.Textarea())

    def save(self):
        instance  = super(AddBook, self).save()
        instance.genre.clear()
        instance.genre.add(*self.cleaned_data['genre'])
        return instance

books/views.py
import json

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse, HttpResponse
from django.utils import timezone
from django.db.models import Q
from django.utils.text import wrap
from django.db.models.functions import Lower

from account.models import Account

from .forms import AddBook
from .models import Book, BookShelf, Downloads, Genre, Language, Rating, Reply, Comment, Barcode

import requests,barcode
from django.core.files import File

# def trial(request):
#     return render(request, 'books/trial2.html')

@login_required
def pdfviewer(request):
    context = {}
    if request.method == 'GET':
        if request.GET['isbn'] :
            context['isbn'] = request.GET['isbn']
            context['book'] = Book.objects.get(isbn = request.GET['isbn'])
            try:
                context['page'] = BookShelf.objects.get(user=request.user, book=context['book']).currentpage
            except BookShelf.DoesNotExist:
                context['page'] = 1
    return render(request, 'books/pdfviewer.html',context)


def home(request):
    context = {}
    context['search'] = True
    if request.user.is_authenticated:
        context['auth'] = True
    allBooks = Book.objects.all()
    context['mostviewed'] = allBooks.order_by('-views')[:12]
    context['new'] = allBooks.order_by('-created_at')[:12]
    return render(request, 'books/index.html', context)

@login_required
def addbook(request):
    context = {}
    context['addbookActive'] = True
    context['auth'] = True
    form = AddBook(initial = {'user':request.user})
    if request.method == 'POST':
        form = AddBook(request.POST, request.FILES, initial = {'user':request.user})
        if form.is_valid():
            book = form.save()
            response = HttpResponse(status=302)
            response['Location'] = '/book?isbn='+str(book.isbn)
            return response
            form = AddBook(initial = {'user':request.user})
    context['form'] = form;
    context['genres'] = Genre.objects.all()
    context['languages'] = Language.objects.all()
    return render(request, 'books/addbook2.html', context)


def bookview(request,isbn=None):
    context = {}
    context['search'] = True
    if request.user.is_authenticated:
        context['auth'] = True
    if request.method=='GET':
        if request.GET.get('isbn'):
            isbn = request.GET.get('isbn')
    if isbn == None:
        return redirect('books:home')
    book = Book.objects.get(isbn=isbn)
    context['book'] = book
    bookrating = Rating.objects.filter(book=book).count()
    if bookrating == 0:
        context['ratingnumber'] = 0
    else:
        context['ratingnumber'] = bookrating
    if request.user.is_authenticated:
        if Rating.objects.filter(book=book, user=request.user).count() == 0:
            context['userRated'] = False
        else:
            context['userRated'] = True
            context['userrating'] = Rating.objects.get(book=book,user=request.user).userrating
    else:
        context['userRated'] = False
    context['comments'] = Comment.objects.filter(book=book).order_by('-created_at')
    context['morefromauthor'] = Book.objects.filter(author=book.author).exclude(isbn=book.isbn)[:6]

    #get or generate barcode
    barcode = gen_or_get_barcode(request)
    context['barcode'] = barcode

    return render(request, 'books/bookview.html', context)



def catview(request):
    context = {}
    context['search'] = True
    context['languages'] = Language.objects.all()
    context['genres'] = Genre.objects.all()
    if request.user.is_authenticated:
        context['auth'] = True
    if request.method == 'POST':
        sort = request.POST.get('sort','az')
        lang = request.POST.get('language','all')
        gen = request.POST.get('category','all')
        print('lang print next')
        print(request.POST.get('category'))
        books = Book.objects.select_related('language').all()
        if lang != 'all':
            language = Language.objects.get(lang=lang)
            books = books.filter(language = language)
        if gen != 'all':
            genre = Genre.objects.get(name=gen)
            books = books.filter(genre=genre)
        if sort == 'az':
            books = books.order_by(Lower('title'))
        elif sort == 'za':
            books = books.order_by(Lower('title')).reverse()
        elif sort == 'no':
            books = books.order_by('-created_at')
        else:
            books = books.order_by('created_at')
        context['cat'] = books
        context['selectedsort'] = sort
        context['selectedlang'] = lang
        context['selectedgen'] = gen
        return render(request, 'books/catview1.html', context)
    if request.method == 'GET':
        cat = request.GET.get('cat')
        context['title'] = cat
        context['cat'] = Book.objects.filter(genre = Genre.objects.get(name = cat))
    return render(request, 'books/catview1.html', context)

@login_required
def search(request):
    context ={}
    context['search'] = True
    if request.user.is_authenticated:
        context['auth'] = True
    context['title'] = 'Search Results'
    if request.method == 'GET':
        q = request.GET.get('search')
        context['cat'] = Book.objects.filter(Q(title__icontains=q) | Q(author__icontains=q) | Q(description__icontains=q))
    return render(request, 'books/searchview.html', context)

@login_required
def addtoshelf(request):
    context = {'status':'err'}
    if request.method == "GET":
        isbn = request.GET.get('isbn')
        book = Book.objects.get(isbn=isbn)
        user = request.user
        try:
            bookadded = BookShelf.objects.filter(book=book).filter(user= Account.objects.get(username=request.user))
            context['status'] = 'pre'
        except BookShelf.DoesNotExist:
            text = Book.objects.get(isbn = isbn)
            text.views+=1
            text.save()
            newbook=BookShelf(user=Account.objects.get(username=request.user), book=text)
            newbook.save()
            context['status'] = 'ok'
        if not bookadded:
            text = Book.objects.get(isbn = isbn)
            text.views+=1
            text.save()
            newbook=BookShelf(user=Account.objects.get(username=request.user), book=text)
            newbook.save()
            context['status'] = 'ok'
    return JsonResponse(context)

def bookshelf(request):
    context = {}
    context['auth'] = False
    context['bookshelfActive'] = True
    context['search'] = True
    if request.user.is_authenticated:
        context['auth'] = True
        context['books'] = BookShelf.objects.filter(user=request.user)
        try:
            context['currentbook'] = context['books'].get(iscurrentbook=True)
            if context['currentbook'].totalpage == 0:
                context['percent'] = 0;
            else:
                context['percent'] = context['currentbook'].currentpage / context['currentbook'].totalpage * 100
        except BookShelf.DoesNotExist:
            pass
    return render(request, 'books/bookshelf1.html', context)

@login_required
def deletebook(request):
    context = {'status':'err'}
    if request.method == 'GET':
        isbn = request.GET.get('isbn')
        try:
            book = Book.objects.get(isbn=isbn)
        except Book.DoesNotExist:
            return JsonResponse(context)
        bookinshelf = BookShelf.objects.filter(book=book).filter(user=request.user)
        bookinshelf.delete()
        context['status'] = 'ok'
    return JsonResponse(context)

@login_required
def setcurrentbook(request):
    if request.method == 'GET':
        try:
            previousbook = BookShelf.objects.get(user=request.user, iscurrentbook=True)
            previousbook.iscurrentbook = False
            previousbook.save()
        except BookShelf.DoesNotExist:
            pass
        isbn = request.GET.get('isbn')
        try:
            book = Book.objects.get(isbn=isbn)
        except Book.DoesNotExist:
            print('Error in getting book')
            return
        item = BookShelf.objects.get(book=book, user=request.user)
        item.iscurrentbook = True
        item.save()
    return

@login_required
def setcurrentpage(request):
    print('got request')
    if request.method == 'GET':
        currentbook = BookShelf.objects.get(user=request.user, iscurrentbook=True)
        pageno = request.GET.get('page')
        totalpage = request.GET.get('total')
        print('in if ')
        if int(pageno) > currentbook.currentpage:
            currentbook.currentpage = pageno
            currentbook.totalpage = int(totalpage)
            currentbook.save()
            print('saved')
    return JsonResponse({'result':'done'})

@login_required
def uploadslist(request):
    context = {}
    context['uploadActive'] = True
    context['search'] = True
    if request.user.is_authenticated:
        context['auth'] = True
    if request.method == 'GET':
        booklist = Book.objects.filter(user=request.user)
        page = request.GET.get('page',1)
        paginator = Paginator(booklist.order_by('-created_at'),10)
        context['books'] = paginator.get_page(page)
        context['length'] = booklist.count()
        context['cat'] = 'Uploads'
        context['upload'] = True
    return render(request, 'books/uploads.html', context)

@login_required
def downloadlist(request):
    context = {}
    context['downloadActive'] = True
    context['search'] = True
    if request.user.is_authenticated:
        context['auth'] = True
    if request.method == 'GET':
        booklist = Downloads.objects.filter(user = request.user)
        page = request.GET.get('page',1)
        paginator = Paginator(booklist.order_by('-created_at'),10)
        context['booksdown'] = paginator.get_page(page)
        context['cat'] = 'Downloads'
        context['download'] = True

books/templates/books/app1.html
<html lang=”en”><head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">    <!-- Name of your awesome camera app -->
    <title>Camera App</title>    <!-- Link to your main style sheet-->
    <link rel="stylesheet" href="{% static 'trial/appstyle.css' %}">
</head><body>    <!-- Camera -->
    <main id="camera">        <!-- Camera sensor -->
        <canvas id="camera--sensor"></canvas>        <!-- Camera view -->
        <video id="camera--view" autoplay playsinline></video>        <!-- Camera output -->
        <img src="//:0" alt="" id="camera--output">        <!-- Camera trigger -->
        <button id="camera--trigger">Take a picture</button>    </main>    <!-- Reference to your JavaScript file -->
    <script src="{% static 'trial/app.js' %}"></script></body></html>

books/templates/books/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>ManyBooks</title>
{% load static %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="ManyBook">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap-4.1.2/bootstrap.min.css' %}">
<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel = "stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>


{% block exlinks %}

{% endblock %}
<script type="text/javascript">
	{% block js %}
	{% endblock %}
	function togglediv(){
		$('.userpopup').toggleClass('showdiv');
	}
</script>
<style media="screen">
{% block css %}
{% endblock %}
.userpopup{
	z-index: 500;
	display: none;
	position: fixed;
	top: 78px;
	right: 3vw;
	width: 12vw;
	background-color: #fff;
	color: #555;
	box-shadow: 0 0 3px 1px #999;
	border-radius: 4px;
}
.showdiv{
	display:block;
}
.item:hover{
	color: #fff;
	background-color: #555;
}
.logout{
	color:red;
}
.logout:hover{
	color: #fff;
	background-color: red;
}
.userpopup ul{
	list-style: none;
	margin: 10px 0;
}
.userpopup ul li{
	padding: 5px 10px;
	cursor: pointer;
	border-bottom: 1px solid #ececec;
	font-size: 1.2em;
}
.userpopup ul li:last-child{
	border-bottom: none;
}
.imgcircle{
	display:block;
	border-radius: 15%;
}

</style>
</head>
<body>

{% block extra %}
{% endblock %}

<div class="userpopup">
	<ul>
		{% if request.user.is_authenticated %}
		<li class="item" onclick="location.href='{% url 'account:update' %}'">Profile</li>
		<li class="item" onclick="location.href='{% url 'password_change' %}'">Change Password</li>
		<li class="logout" onclick="location.href='{% url 'account:logout' %}'">Logout</li>
		{% else %}
		<li class="item" onclick="location.href='{% url 'account:register' %}'">Sign Up</li>
		<li class="item" onclick="location.href='{% url 'login' %}?next={{request.path}}'">Sign In</li>
		{% endif %}
	</ul>
</div>

<!-- Menu -->

<div class="menu">
	<div class="menu_nav">
		<ul>
			<li  style="font-family: 'Roboto', sans-serif;"
					 {% if bookshelfActive %}
							class="active"
					 {% endif %}><a {% if auth %}
					 href="{% url 'books:bookshelf' %}"
					 {% else %}
					 href="{% url 'account:login' %}"
					 {% endif %}>Bookshelf</a></li>
			<li style="font-family: 'Roboto', sans-serif;"
					 {% if uploadActive %}
							class="active"
					 {% endif %}>
					 <a {% if auth %}
							href="{% url 'books:uploadslist' %}"
					 {% else %}
							href="{% url 'account:login' %}"
					 {% endif %}>Uploads</a></li>
			<li style="font-family: 'Roboto', sans-serif;"
					 {% if downloadActive %}
							class="active"
					 {% endif %}><a {% if auth %}
					 href="{% url 'books:downloadlist' %}"
					 {% else %}
					 href="{% url 'account:login' %}"
					 {% endif %}>Downloads</a></li>
		</ul>
	</div>
</div>

<div class="super_container">

	<!-- Header -->

	<header class="header">
		<div class="header_overlay"></div>
		<div class="row">
			<div class="col-sm-1">
				<div class="header_content d-flex flex-row align-items-center justify-content-start">
					<div class="hamburger"><i class="fa fa-bars" aria-hidden="true"></i></div>
				</div>
			</div>
			<div class="col-sm-11">
				<div class="header_content d-flex flex-row align-items-center justify-content-start">
					<div class="logo">
						<a href="{% url 'books:home' %}">
							<div class="d-flex flex-row align-items-center justify-content-start">

								<div>ManyBooks</div>
							</div>
						</a>
					</div>

					<nav class="main_nav active">
						<ul id='mainnav' class="d-flex flex-row align-items-start justify-content-start">
							<li  style="font-family: 'Roboto', sans-serif;"
									 {% if bookshelfActive %}
											class="active"
									 {% endif %}><a {% if auth %}
									 href="{% url 'books:bookshelf' %}"
								   {% else %}
									 href="{% url 'account:login' %}"
								   {% endif %}>Bookshelf</a></li>
							<li style="font-family: 'Roboto', sans-serif;"
									 {% if uploadActive %}
											class="active"
									 {% endif %}>
									 <a {% if auth %}
											href="{% url 'books:uploadslist' %}"
								   {% else %}
											href="{% url 'account:login' %}"
								   {% endif %}>Uploads</a></li>
							<li style="font-family: 'Roboto', sans-serif;"
									 {% if downloadActive %}
											class="active"
									 {% endif %}><a {% if auth %}
									 href="{% url 'books:downloadlist' %}"
								   {% else %}
									 href="{% url 'account:login' %}"
								   {% endif %}>Downloads</a></li>
						</ul>
					</nav>
					<div class="header_right d-flex flex-row align-items-center justify-content-start ml-auto">
						<!-- Search -->
						{% if search %}
						<div class="header_search">
							<form action="{% url 'books:search' %}" id="header_search_form" method="get">
								<input name="search" id="search"  type="text" class="search_input" placeholder="Search for books" required="required">
								<button class="header_search_button"><img src="{% static 'images/search.png' %}" alt=""></button>
							</form>
						</div>
						{% endif %}
						<!-- User -->
						<div style="padding-right:10px;">
							<p style="color:#333;">{{request.user.username|title}}</p>
						</div>
						<div class="user">
							<a onclick="togglediv()">
								<div>
									<img id='userpic'  height='26px' width="26px" class="imgcircle" src="{% if request.user.is_authenticated %}
																							{% if request.user.userpic %}
																								{{user.userpic.url}}
																							{% else %}
																								{% static 'images/user.svg' %}
																							{% endif %}
																							{% else %}
																								{% static 'images/user.svg' %}
																							{% endif %}">
								</div>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>


	</header>

	<div class="super_container_inner">
		<div class="super_overlay"></div>

        {% block content %}
        {% endblock %}

        <!-- Footer -->

        <footer class="footer">

            <div class="footer_bar">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="footer_bar_content d-flex flex-md-row flex-column align-items-center justify-content-start">
                                <div class="copyright order-md-1 order-2"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    </div>

    <!-- <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script> -->
    <script src="{% static 'styles/bootstrap-4.1.2/popper.js' %}"></script>
    <script src="{% static 'styles/bootstrap-4.1.2/bootstrap.min.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.js" crossorigin="anonymous"></script>
    <script src="{% static 'plugins/greensock/TweenMax.min.js' %}"></script>
    <script src="{% static 'plugins/greensock/TimelineMax.min.js' %}"></script>
    <script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js' %}"></script>
    <script src="{% static 'plugins/greensock/animation.gsap.min.js' %}"></script>
    <script src="{% static 'plugins/greensock/ScrollToPlugin.min.js' %}"></script>
    <script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
    <script src="{% static 'plugins/easing/easing.js' %}"></script>
    <script src="{% static 'plugins/progressbar/progressbar.min.js' %}"></script>
    <script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    </body>
</html>

books/templates/books/captureTrial.html
<!doctype html>
<html>
<head>
	{% load static %}
	<title>WebRTC: Still photo capture demo</title>
	<meta charset='utf-8'>
	<link rel="stylesheet" href="{% static 'trial/maincapture.css' %}" type="text/css" media="all">
	<script src="{% static 'trial/capture.js' %}">
	</script>
</head>
<body>
<div class="contentarea">
	<h1>
		MDN - WebRTC: Still photo capture demo
	</h1>
	<p>
		This example demonstrates how to set up a media stream using your built-in webcam, fetch an image from that stream, and create a PNG using that image.
	</p>
  <div class="camera">
    <video id="video">Video stream not available.</video>
    <button id="startbutton">Take photo</button>
  </div>
  <canvas id="canvas">
  </canvas>
  <div class="output">
    <img id="photo" alt="The screen capture will appear in this box.">
  </div>
	<p>
		Visit our article <a href="https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos"> Taking still photos with WebRTC</a> to learn more about the technologies used here.
	</p>
</div>
</body>
</html>